name: CI

on:
pull_request:
branches:
- main # или ветка, в которую вливаешь PR

jobs:
build-and-test:
runs-on: ubuntu-latest

steps:
- uses: actions/checkout@v3
- name: Установить Node.js
uses: actions/setup-node@v3
with:
node-version: '18'

- name: Установить зависимости
run: npm install

- name: Запустить тесты
run: npm test

- name: Запустить линтер
run: npm run lint
