name: Docker Build, Scan, and Deploy

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: your-app-name
  VM_IP: your-azure-vm-ip
  VM_USERNAME: your-vm-username
  VM_SSH_KEY: ${{ secrets.VM_SSH_PRIVATE_KEY }}

jobs:
  build-scan-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t $IMAGE_NAME .

    - name: Install Trivy
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'image'
        image-ref: $IMAGE_NAME
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'

    - name: Save Docker image as artifact
      run: docker save -o image.tar $IMAGE_NAME

    - name: Deploy to Azure VM
      uses: appleboy/scp-action@master
      with:
        host: ${{ env.VM_IP }}
        username: ${{ env.VM_USERNAME }}
        key: ${{ env.VM_SSH_KEY }}
        source: "image.tar"
        target: "/home/${{ env.VM_USERNAME }}/"

    - name: Load and run image on VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.VM_IP }}
        username: ${{ env.VM_USERNAME }}
        key: ${{ env.VM_SSH_KEY }}
        script: |
          docker load -i /home/${{ env.VM_USERNAME }}/image.tar
          docker stop $IMAGE_NAME || true
          docker rm $IMAGE_NAME || true
          docker run -d --restart unless-stopped -p 3000:3000 --name $IMAGE_NAME $IMAGE_NAME